### ISSUE TITLE
No maps visible on Alcatel OT 6012D with Android 4.2.2

### ISSUE THREAD

**Issue by uvwild** [c3nav/c3nav-android#11]
Showing the found route on a  480x854 pixel display is not showing any maps.

**Comment by NoMoKeTo** [comment]
Cannot reproduce.

![download](https://cloud.githubusercontent.com/assets/3868507/12121112/f1829582-b3d3-11e5-82d4-cfb9c8d32243.png)

**Comment by uvwild** [comment]
On android 4.2.2  no maps are shown.

**Comment by NoMoKeTo** [comment]
@uvwild It would be very much more welcome if you just posted a bunch of technical details about your device that has the problem. Are you sure that it happens on every device running android 4.2.2. If not so, please post more information about your device. Thank you.

**Comment by uvwild** [comment]
never mind - its an old phone - however the only use case I had and it failed :(
Alcatel OT 6012D
firmware 4.2.2
kernel version 3.4.5 
android-bld@Perso71 #1

I will try to find an emulator configuration  in android studio to reproduce. 
Looks like the svg tag does not get rendered properly on some devices.

**Comment by codingcatgirl** [comment]
Everything is new in c3nav now, so this bug is no longer relevant.
