### ISSUE TITLE
Blank screen, only "Open in…" showing

### ISSUE THREAD

**Issue by pludi** [c3nav/c3nav-android#13]
App-Version: 3.1 from Google Play
Android: 8.1.0
Mobile: Bq Aquaris X Pro

Opening the App only shows a blank screen, and the "Open with…" dialog. Blank screen also overlays the lock screen.

Screen recording: https://peertube.social/videos/watch/c1502271-6039-468f-8eac-f382a16ac0ef

**Comment by codingcatgirl** [comment]
Version 3.1 is no longer supported, as it is the version for the 34c3, so naturally it doesn't work.

Please update.
