### ISSUE TITLE
35c3 version on f-droid

### ISSUE THREAD

**Issue by Bubu** [c3nav/c3nav-android#14]
The main f-droid buildserver is currently not progressing, so chances are the 35C3 won't make it into the main repo before/during congress.

We set up a dedicated Congress repo here https://fdroid.gitlab.io/35c3/fdroid/repo/ though. Please direct people ther eto get the latest version via f-droid.

Also please ping me if I need to update this with newer versions.

(Ref: https://mastodon.technology/@fdroidorg/101307515709545032)

**Comment by codingcatgirl** [comment]
We retweeted the announcement.
