### ISSUE TITLE
Webpage not available. 

### ISSUE THREAD

**Issue by cckole** [c3nav/c3nav-android#19]
### Description
On launching the app, I was welcome with webpage not available. Also, account cannot be managed and the map isn't loading as well.

### Screen shot

![Screenshot_20190517-135046](https://user-images.githubusercontent.com/36272218/57929579-9bcaa300-78ab-11e9-826e-8242e0652e00.png)

### Device used

Techno spark k7.
Android 7.0

**Comment by codingcatgirl** [comment]
So, what were you expecting? There is no c3nav at any event right now.

**Comment by johnjohndoe** [comment]
Although what @codingcatgirl wrote is true I think it would be nice if the app would welcome users with a "fallback" screen which nicely hides the browser response.

**Comment by codingcatgirl** [comment]
Sure, but that's not a priority at this time of year.
