### ISSUE TITLE
Feat: Update custom position using phone location

### ISSUE THREAD

**Issue by v411e** [c3nav/c3nav-android#25]
Hi, what do you think about a feature where (e.g. in the settings screen) a custom position could be specified that automatically gets updated with the current phone location once the App is active?

**Comment by codingcatgirl** [comment]
For that we would need to track you in the background, that's currently not planned.

**Comment by v411e** [comment]
Ah, I just read some code. This also would probably rather be implemented somewhere in https://github.com/c3nav/c3nav/blob/a4b72478fadd4eae60b71046fa4c46dc9b914003/src/c3nav/site/static/site/js/c3nav.js because c3nav-android just provides a JS interface and does not contain the logic for positioning etc (as far as I can tell)

**Comment by codingcatgirl** [comment]
Not entirely correct. If we actually wanted to track you in the background, we would have to implement it on an app level. Doing that using the wrapper might be impossible or at least very bad for battery usage.
