### ISSUE TITLE
(37C3) version for F-Droid / fdroid outdated

### ISSUE THREAD

**Issue by dhebbeker** [c3nav/c3nav-android#27]
The current version of c3nav on the official F-Droid repositories is about 4 years old.

Maybe it would be better to remove the link to F-Droid so that one does not have to wonder what is the issue.

**Comment by p-fruck** [comment]
I think auto updates have been broken for a while, but they should be fixed now since F-Droid auto update already [added](https://gitlab.com/fdroid/fdroiddata/-/commit/93ee00c972b2c7f4faee53b2390646eb4811ccbe) metadata for v4.2.4. Might take a while for F-Droid to build and update the app though

**Comment by codingcatgirl** [comment]
Simply put. F-Droid is slow. It sucks. We can't recommend it :/

But you can just use our own F-Droid repo now: https://f-droid.c3nav.de/fdroid/repo/?fingerprint=C1EC2D062F67A43F87CCF95B8096630285E1B2577DC803A0826539DF6FB4C95D
