### ISSUE TITLE
FR: add support for other maps

### ISSUE THREAD

**Issue by thibaultmol** [c3nav/c3nav-android#29]
Hi, for FOSDEM we're using a c3nav web instance to host the map for a couple years now and it's great.
https://nav.fosdem.org/

A problem we're facing is that the android app of C3nav (which any c3nav web instance will link to when you try to activate the geo location feature) only supports the ccc map. It would be nice if there was a way to have the fosdem map shown in there.

While ideally when you open the app for the first time, it should ask if you want the ccc map or the fosdem (or another map), I understand that this might be asking too much.

So maybe having a setting in the app would be nice and maybe also having a way of deep linking to the fosdem map. So someone can click `de.c3nav.droid://nav.fosdem.org/api/` and it would open the C3nav app to the fosdem map (and stay on the fosdem map even if the app restarts. But the user can go back to the 'default' map using a setting or button

**Comment by codingcatgirl** [comment]
Hi!

ths codebase absolutely supports other maps! However, we are currently not planning to add support for c3nav installations that are not set up by our team.

There's a few reasons why this would impractical, be it certificate pinning, URL handlers  theming/design that fits the event and of course also having to having to talk to servers that are not under our control (and we need to supply data privacy URLs etc to publish this app on the app stores).

If you build a dev build of the app, you can already freely set the URL. Nothing is stopping you from publishing your own app for instances that you self host, just like it's also done for many open source schedule apps – in fact, we encourage it :)

**Comment by thibaultmol** [comment]
I see, the reason why I asked is because it didn't really seem worth it to get publish a fork of the app (atleast not for IOS, because of the 300 $ yearly developer fee.)
But I didn't realize it would have been so much work to implement this, no problem

**Comment by codingcatgirl** [comment]
I can reassure you when it comes to the iOS issue. We don't have an iOS app :D

**Comment by thibaultmol** [comment]
My apologies! I'm not sure why I thought that there was an iOS version. That does simplify things then, thank you!
