### ISSUE TITLE
Adding documentation about using Bluetooth beacons

### ISSUE THREAD

**Issue by thibaultmol** [c3nav/c3nav-android#30]
Hi, I saw that bluetooth beacon support was added. I'm curious how exactly this works and how one could deploy bluetooth beacons for a custom (non-ccc) event (like FOSDEM).

I'm not asking for too much documentation, but even just links to resources and how it integrates in c3nav would be good. thank you

**Comment by codingcatgirl** [comment]
Unfortunately, this is so far, for the most, only support on the app so we can eperiment with it at events that we visit. So it's currently experimental and not something that c3nav officially supports yet. Ask us again after congress, it might have changed by then :)
