### ISSUE TITLE
Release c3nav 3.4.0 (github release/playstore/f-droid)

### ISSUE THREAD

**Issue by teneko** [c3nav/c3nav-android#32]
In two days the 38C3 in Hamburg officially begins, so it would be awesome when I could tell my chaos mentees, that the app is officially updated for 38C3. Currently the app is blank once opened and crashes when clicking on Login, likely due to the fact that the links of the older events are not available anymore.

I downloaded the source code, compiled it and installed the debug variant on my phone, and it seems it just works as expected; no crash anymore, thankfully to the latest commits made by you.

By the way, android studio seems not to find the gradle tasks like assembleDebug, actually none at all, expect testDebugUnitTest and testReleaseUnitTest. Even by using the gradle wrapper (`gradlew.bat tasks`), the assembleDebug task is not listed. I just came across the android documentation that stated to use the assembleDebug task, so I blindly ran it against gradlew (`gradlew.bat assembleDebug`) after installing the Java Developement Kit 23 manually.

A README.md for how to work with the source code would be phenomenal.

**Comment by codingcatgirl** [comment]
Than you for taking the time to write an long extensive Issue telling us to
release something that we are clearly working on releasing.

We can assure you, it will be released before Congress and an issue like
this to pressure us to work faster is disrespectful. Thank you and have a
nice day.

**Comment by teneko** [comment]
Oh this was not meant to be disrespectful. Your honor just dropped by -100.

Be aware that I for sure did not want to preasure, instead you should be optimistic and see the more the good. I clearly cannot see anything offending, it's simply a small report. Imaging being a customer, opening the app and seeing 2 days before it does not work, next to the official "c3nav - 37c3 indoor navigation" title referring to another event. Do you not think that someone is keen to ask whether the app is still about to release?

Anyway, I am glad the app works.

I surely won't disturb/contribute anymore and take my star with me.

**Comment by gwenya** [comment]
> Imaging being a customer

I’m not aware of c3nav having customers. Paid support is available on request though.

**Comment by codingcatgirl** [comment]
Teneko, i genuinely can only recommend you reconsider your view and sentiments in regard to the chaos community and how the Chaos Communication Congress is organized by volunteers before you give any wrong impressions to your mentees.

It's the 23rd of Decemember, 4 days before the start of the eveent, c3nav is publicly available at https://38c3.c3nav.de and any benefit that the app provides is only useful on site – and not even now, cause we haven't calibrated wifi positioning yet.

We don't have customers. We are not a professional service provider. We are not a company. Nothing about congress is, in practice. This is an event organized by volunteers. Chaos happens normally, at congress. Many things are available late. This is how it works. Your complaint show a truly miraculous misunderstanding of the entire event. 

Feel free to take your star with you, if that makes you feel better…?

As a site note, the app is actually not done. The logo and other graphics still need to be updated for congress.

**Comment by teneko** [comment]
It makes me wonder how you imply several time things out of context. You implied I would pressure you, I would see in you a paid service/company, then that I would (or will) give a wrong expression to my mentees, does that make you feel better?

Why you cannot imply the following: someone tests the app, someone wants to volunteer to the app, improve it in case it still shows blank page or crashes on click, someone who wants (now wanted) to improve documentation how to work with/compile the app, or imply that the app is getting more visible to third party and more people _may_ get confused and _maybe_ wants clarity/predictability.

Your reaction shows almost an agressive tenor. You really should reconsider your wording and your attitude. Your first answer was completely offset. Sorry but reacting like this and then talking about the soul of what CCC stand for is really hypocrisy.

**Comment by johnjohndoe** [comment]
@teneko From what I experienced in other Android projects the mentioned tasks might be missing because Gradle cannot complete its configuration phase due to the lack of signing keys. Without testing it myself locally, I suggest you temporarily comment out the signing config and `release` build type, see *app/build.gradle.kts`.

**Comment by codingcatgirl** [comment]
> You really should reconsider your wording and your attitude. Your first answer was completely offset. 

Thank you for your opinion. I politely disagree. Thank you for your understanding.
